### PR TITLE
Update to symfony 5.0

### PR DESCRIPTION
**Pull request by romainf**
This PR is based on @jkhaled PR but for 4.1.0 (his work is for 3.2.0).

Symfony package require ~5.0
PHP minimal version up to 7.2.5 because of symfony/framework-bundle:~5.0 dependencies.

### CODE REVIEW

**Comment by remmel** [comment]
Is that a good idea to remove Symfony 3 and 4 support?

**Comment by romainf** [comment]
@remmel I found a break change in Sf 4.2
#### "DependencyInjection/Configuration.php"
Before 4.2:
```
$treeBuilder = new TreeBuilder();
$rootNode  = $treeBuilder->root('florianv_swap');
```

Since 4.2:
```
$treeBuilder = new TreeBuilder('florianv_swap');
$rootNode  = $treeBuilder-> getRootNode();
```

So restoring support for Sf ^4.2 ans php ^5.6 make sense.

**Comment by florianv** [comment]
@romainf Thanks for your PR :)

Is it possible to keep support for the previous Symfony versions ?

FYI, this PR will be part of the `5.0` release of the Bundle.

**Comment by romainf** [comment]
@florianv done

**Comment by florianv** [comment]
Thanks @romainf 👍 

Releasing a new major version now!

**Pull request merged**
