### PR TITLE
Updated swap to ~3.0.

### PR DESCRIPTION
**Pull request by ekyna**
(Dropped support of php 5.5)

### CODE REVIEW

**Comment by ekyna** [comment]
Fixes #12

**Comment by florianv** [comment]
Hey @ekyna,

Thanks a lot for this pull request and hard work! I've been wanting to do it for a long time, but never found the time :(

Everything looks good to me 👍

**Comment by ekyna** [comment]
You're welcome ! And thanks to you for the Swap lib ;)

**Comment by florianv** [comment]
@ekyna Do you think it's ready for a release ? I don't use Symfony these days :/

**Comment by ekyna** [comment]
I'm using it in a production project, so it sounds good. If problems appends i will do subsequent PRs, but it should be ok.

**Comment by florianv** [comment]
Thanks a lot @ekyna. I will make a new release.
Would you like to become a maintainer of the bundle ?

**Comment by ekyna** [comment]
This bundle should be ok until Swap evolves. And it's better if you review the code before merging... But if you think you won't have enough time, i can manage it.

**Pull request merged**
